gpu:
	python explanation_mem_gpu.py MMBT lime
	python explanation_mem_gpu.py MMBT shap
	python explanation_mem_gpu.py MMBT torchray
	python explanation_mem_gpu.py LateFusion lime
	python explanation_mem_gpu.py LateFusion shap
	python explanation_mem_gpu.py LateFusion torchray
	python explanation_mem_gpu.py ViLBERT lime
	python explanation_mem_gpu.py ViLBERT shap
	python explanation_mem_gpu.py ViLBERT torchray
	python explanation_mem_gpu.py VisualBERT lime
	python explanation_mem_gpu.py VisualBERT shap
	python explanation_mem_gpu.py VisualBERT torchray

gpu_debug:
	python explanation_mem_gpu.py VisualBERT torchray
	python explanation_mem_gpu.py ViLBERT torchray

cpu:
	python explanation_mem_cpu.py MMBT lime
	python explanation_mem_cpu.py MMBT shap
	python explanation_mem_cpu.py MMBT torchray
	python explanation_mem_cpu.py LateFusion lime
	python explanation_mem_cpu.py LateFusion shap
	python explanation_mem_cpu.py LateFusion torchray
	python explanation_mem_cpu.py ViLBERT lime
	python explanation_mem_cpu.py ViLBERT shap
	python explanation_mem_cpu.py ViLBERT torchray
	python explanation_mem_cpu.py VisualBERT lime
	python explanation_mem_cpu.py VisualBERT shap
	python explanation_mem_cpu.py VisualBERT torchray